# Generated by Django 2.2.5 on 2022-07-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20220723_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='', max_length=80),
        ),
    ]
