# Generated by Django 2.2.5 on 2022-07-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestempedmodel',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timestempedmodel',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
